name: ra12451_pandas
dependencies:
- cairo=1.12.18=5
- decorator=4.0.4=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- hdf5=1.8.15.1=2
- ipython=4.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- libgfortran=1.0=0
- libpng=1.6.17=0
- libxml2=2.9.2=0
- matplotlib=1.4.3=np110py27_2
- numexpr=2.4.4=np110py27_0
- numpy=1.10.1=py27_0
- openblas=0.2.14=3
- openssl=1.0.2d=0
- pandas=0.17.0=np110py27_0
- path.py=8.1.2=py27_0
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- pixman=0.26.2=0
- py2cairo=1.10.0=py27_2
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_0
- pytables=3.2.2=np110py27_0
- python=2.7.10=2
- python-dateutil=2.4.2=py27_0
- pytz=2015.6=py27_0
- qt=4.8.7=1
- readline=6.2=2
- setuptools=18.4=py27_0
- simplegeneric=0.8.1=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.8.4.1=1
- tk=8.5.18=0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- zlib=1.2.8=0
- pip:
  - dxr==0.1
  - futures==2.2.0
  - ipython-genutils==0.1.0
  - jinja2==2.7.2
  - markupsafe==0.23
  - networkx==1.8.1
  - ordereddict==1.1
  - parsimonious==0.6.1
  - pydablooms==0.9.1
  - pygments==1.6
  - pyminuit2==0.0.1
  - python-ldap==2.4.10
  - rivet==2.2.0
  - scipy==0.8.0
  - tables==3.2.2
  - yoda==1.3.0

